
CREATE TABLE ProductModelEntity (
    ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
    ModelName VARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE ProductOrderEntity (
    ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
    OrderDate DATE NOT NULL
);


CREATE TABLE ProductDetailsEntity (
    ID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
    Color VARCHAR(50) NOT NULL,
    Description VARCHAR(MAX) NOT NULL
);


CREATE TABLE ProductEntity (
    ProductID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
    ProductName VARCHAR(50) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    ProductOrderEntityID UNIQUEIDENTIFIER NOT NULL,
    ProductDetailsEntityID UNIQUEIDENTIFIER NOT NULL,
    ProductModelEntityID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (ProductOrderEntityID) REFERENCES ProductOrderEntity(ID),
    FOREIGN KEY (ProductDetailsEntityID) REFERENCES ProductDetailsEntity(ID),
    FOREIGN KEY (ProductModelEntityID) REFERENCES ProductModelEntity(ID)
);


CREATE TABLE CategoryEntity (
    CategoryID UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
    CategoryName VARCHAR(50) NOT NULL UNIQUE,
    ProductID UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (ProductID) REFERENCES ProductEntity(ProductID)
);
